controller_list:
  - name: fake_Quad_base_controller
    type: $(arg fake_execution_type)
    joints:
      - base_to_world
initial:  # Define initial robot poses per group
#  - group: Quad_base
#    pose: home

  []